baseURL: "https://www.nurullahpolat.com/"
languageCode: en-us
title: "Nurullah POLAT"
theme: LoveIt-master

languages:
  en:
    languageName: English
    weight: 1
  tr:
    languageName: Türkçe
    weight: 2
